<?php

namespace SdsCommon\Test;

use SdsCommon\TraitHelper;

/**
 * Test class for TraitHelper.
 * Generated by PHPUnit on 2012-06-06 at 14:27:15.
 */
class TraitHelperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TraitHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TraitHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SdsCommon\TraitHelper::getAllTraits
     * @todo Implement testGetAllTraits().
     */
    public function testGetAllTraits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SdsCommon\TraitHelper::getAllParents
     * @todo Implement testGetAllParents().
     */
    public function testGetAllParents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SdsCommon\TraitHelper::checkForTrait
     * @todo Implement testCheckForTrait().
     */
    public function testCheckForTrait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
